### ISSUE TITLE
Error: Node type UnaryExpression not found

### ISSUE THREAD

**Issue by hrdwdmrbl** [it-ony/jscop#1]
I get this hundreds of times!

<pre><code>
/Users/marc/workspace/spike/jscop/lib/nodes/AstNode.js:46
                    throw new Error("Node type " + type + " not found");
                          ^
Error: Node type UnaryExpression not found
    at module.exports.inherit.Base.inherit.initializeChildren (/Users/marc/workspace/spike/jscop/lib/nodes/AstNode.js:46:27)
    at module.exports.AstNode.inherit._initialize (/Users/marc/workspace/spike/jscop/lib/nodes/LogicalExpressionNode.js:7:14)
    at module.exports.inherit.Base.inherit.initialize (/Users/marc/workspace/spike/jscop/lib/nodes/AstNode.js:16:14)
    at module.exports.inherit.Base.inherit.initializeChildren (/Users/marc/workspace/spike/jscop/lib/nodes/AstNode.js:41:26)
    at module.exports.AstNode.inherit._initialize (/Users/marc/workspace/spike/jscop/lib/nodes/IfStatementNode.js:15:34)
    at module.exports.inherit.Base.inherit.initialize (/Users/marc/workspace/spike/jscop/lib/nodes/AstNode.js:16:14)
    at module.exports.inherit.Base.inherit.initializeChildren (/Users/marc/workspace/spike/jscop/lib/nodes/AstNode.js:41:26)
    at module.exports.AstNode.inherit._initialize (/Users/marc/workspace/spike/jscop/lib/nodes/BlockStatementNode.js:6:14)
    at module.exports.inherit.Base.inherit.initialize (/Users/marc/workspace/spike/jscop/lib/nodes/AstNode.js:16:14)
    at module.exports.inherit.Base.inherit.initializeChildren (/Users/marc/workspace/spike/jscop/lib/nodes/AstNode.js:41:26)

</pre></code>

**Comment by it-ony** [comment]
@jackquack you' re right, I non of my code I've used such an expression so I haven't spotted it during development time.

```
y = +1
```

is an unary expression.

I'll add support

**Comment by hrdwdmrbl** [comment]
Thanks!

**Comment by it-ony** [comment]
I found also that try, catch is currently not supported...
